name: Deploy Docker App

on:
  push:
    branches:
      - main

jobs:
  deploy-server1:
    runs-on: [self-hosted, server1]
    environment: production

    steps:
      - name: Atualizar repositório local no server1
        run: |
          cd /home/suporte/newdepl
          git fetch origin
          git reset --hard origin/main

      - name: Rebuild e subir containers no server1
        run: |
          cd /home/suporte/newdepl
          docker compose down || true
          docker compose up -d --build

      - name: Mostrar status no server1
        run: |
          cd /home/suporte/newdepl
          docker compose ps

  deploy-server2:
    runs-on: [self-hosted, server2]
    environment: production

    steps:
      - name: Atualizar repositório local no server2
        run: |
          cd /home/suporte/newdepl
          git fetch origin
          git reset --hard origin/main

      - name: Rebuild e subir containers no server2
        run: |
          cd /home/suporte/newdepl
          docker compose down || true
          docker compose up -d --build

      - name: Mostrar status no server2
        run: |
          cd /home/suporte/newdepl
          docker compose ps
