name: Rollback Docker App

on:
  workflow_dispatch:
    inputs:
      target_ref:
        description: "Tag ou commit para rollback"
        required: true
        default: "main"

jobs:
  rollback-server1:
    runs-on: [self-hosted, server1]
    environment: production

    steps:
      - name: Buscar commits e tags no server1
        run: |
          cd /home/suporte/newdepl
          git fetch --all --tags

      - name: Aplicar rollback no server1
        run: |
          cd /home/suporte/newdepl
          git reset --hard ${{ github.event.inputs.target_ref }}

      - name: Rebuild e subir containers no server1
        run: |
          cd /home/suporte/newdepl
          docker compose down || true
          docker compose up -d --build

      - name: Mostrar status no server1
        run: |
          cd /home/suporte/newdepl
          docker compose ps

  rollback-server2:
    runs-on: [self-hosted, server2]
    environment: production

    steps:
      - name: Buscar commits e tags no server2
        run: |
          cd /home/suporte/newdepl
          git fetch --all --tags

      - name: Aplicar rollback no server2
        run: |
          cd /home/suporte/newdepl
          git reset --hard ${{ github.event.inputs.target_ref }}

      - name: Rebuild e subir containers no server2
        run: |
          cd /home/suporte/newdepl
          docker compose down || true
          docker compose up -d --build

      - name: Mostrar status no server2
        run: |
          cd /home/suporte/newdepl
          docker compose ps
